module.exports = {
  classes: [
    {
      id: 1,
      race: 'human',
      kind: 'warrior',
      element: 'water',
      people: [
        {
          name: 'Felipe',
          level: 112,
          hp: 10000,
          mp: 1000,
          atk: 1000,
          age: 87,
          city: 'San Andreas',
        },
        {
          name: 'Pedro',
          level: 999,
          hp: 18000,
          mp: 2000,
          atk: 2000,
          age: 100,
          city: 'Espirito Grande',
        },
        {
          name: 'Mike',
          level: 23,
          hp: 14000,
          mp: 3000,
          atk: 1000,
          age: 55,
          city: 'San Andreas',
        },
        {
          name: 'Anderson',
          level: 88,
          hp: 1200,
          mp: 888,
          atk: 888,
          age: 24,
          city: 'Espirito Grande',
        },
      ],
    },
    {
      id: 2,
      race: 'elf',
      kind: 'mage',
      element: 'wind',
      people: [
        {
          name: 'Arn',
          level: 112,
          hp: 10000,
          mp: 1200,
          atk: 1000,
          age: 878,
          city: 'Aracuju de Janeiro',
        },
        {
          name: 'Aysllan',
          level: -100,
          hp: -100,
          mp: -100,
          atk: -100,
          age: -100,
          city: 'Bali',
        },
        {
          name: 'Nati',
          level: 888,
          hp: 1420,
          mp: 1200,
          atk: 1200,
          age: 55000,
          city: 'Bali',
        },
      ],
    },
    {
      id: 3,
      race: 'dwarf',
      kind: 'healer',
      element: 'fire',
      people: [
        {
          name: 'Baunilha',
          level: 142,
          hp: 10000,
          mp: 1200,
          atk: 1000,
          age: 878,
          city: 'Bali',
        },
        {
          name: 'Dani-boy',
          level: 112,
          hp: 1200,
          mp: 3000,
          atk: 2000,
          age: 13,
          city: 'Trybewarts',
        },
        {
          name: 'Fran',
          level: 100,
          hp: 1420,
          mp: 1000,
          atk: 900,
          age: 12000,
          city: 'Sao Horizonte',
        },
      ],
    },
  ],
  maps: [
    {
      id: 1,
      name: 'Bali',
    },
    {
      id: 2,
      name: 'Aracuju de Janeiro',
    },
    {
      id: 3,
      name: 'Sao Horizonte',
    },
    {
      id: 4,
      name: 'San Andreas',
    },
    {
      id: 5,
      name: 'Espirito Grande',
    },
    {
      id: 6,
      name: 'Trybewarts',
    },
  ],
};
